In [36]:
import numpy as np


Array Creation Function

In [3]:
a=np.array([1,2,3])
print("Array a", a)

Array a [1 2 3]


In [4]:
b=np.arange(0,10,2)
print("Array a", b)

Array a [0 2 4 6 8]


In [5]:
d=np.zeros((2,3))
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
e=np.ones((3,2),dtype=int)
print("Array d:\n",e)

Array d:
 [[1 1]
 [1 1]
 [1 1]]


In [8]:
f=np.eye(4)
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


print("Array d:\n",e)

In [11]:
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(3,1))
reshaped

array([[1],
       [2],
       [3]])

In [12]:
f1=np.array([[1,2],[3,4]])
flattened=np.ravel(f1)
flattened

array([1, 2, 3, 4])

In [13]:
e1=np.array([[1,2],[3,4]])
transposed=np.transpose(e1)
transposed

array([[1, 3],
       [2, 4]])

In [14]:
a2=np.array([1,2])
b2=np.array([3,4])

In [18]:
vertical=np.vstack(a2)
stacked=np.vstack([a2,b2])
stacked
stacked1=np.hstack([a2,b2])
stacked1

array([1, 2, 3, 4])

In [19]:
x=5
y=x
x=10
print(y)

5


In [26]:
for i in range(5):
    if i == 2:
      continue
    if i==4:
        break
        print(i,end=" ")

In [28]:
mylist=[1,2,3]
mylist.append([4,5])
len(mylist)

4

In [29]:
nums=[1,2,3,4]
result=[x*2 for x in nums if x%2==0]
result

[4, 8]

In [32]:
a=[[0]*3]*3
a[0][1]=5
print(a)

[[0, 5, 0], [0, 5, 0], [0, 5, 0]]


In [35]:
d={'a':10,'b':20,'c':30}
value=d.pop('b')
print(value,d)

20 {'a': 10, 'c': 30}
