In [4]:
import numpy as np

Important NumPy Concepts Summary
ndarray   --------	main data structure
indexing  ---------	access elements
slicing	  --------- subset arrays
reshaping ---------	change dimensions
broadcasting ------	operations on different shapes
vectorization ---	fast math operations
aggregation	 -------statistical calculations
linear algebra ----	matrix operations

In [5]:
np.__version__

'2.3.5'

In [6]:
mylist=[0,1,2,3,4,5]
mylist

[0, 1, 2, 3, 4, 5]

In [7]:
arr=np.array(mylist)

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr=np.array([1,2,3,4,5])
arr2=np.array([[6,7,8],[9,10]])
arr2

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [10]:
arr2=np.array([[6,7,8],[9,10,11]])
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

 zeros=np.zeros((2,2))
zeros

In [11]:
ones=np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
eye=np.eye(3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
arr_range=np.arange(1,10,2)
arr_range

array([1, 3, 5, 7, 9])

In [14]:
arr_line=np.linspace(0,12,3)
arr_line

array([ 0.,  6., 12.])

================Array Properties===================

In [15]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
print(arr.shape)

(2, 4)


In [17]:
arr.ndim

2

In [18]:
arr.size

8

In [19]:
arr.dtype

dtype('int64')

In [20]:
a1=np.array(['Radha','Narayan'])
print(a1.dtype)
'''shape → dimensions of array
ndim → number of dimensions
dtype → type of elements
size → total number of elements'''

<U7


'shape → dimensions of array\nndim → number of dimensions\ndtype → type of elements\nsize → total number of elements'

In [21]:
c1=np.array([10,20,30,40,50,60,70,80])
print(c1[0])
print(c1[-1])
print(c1[:])
print(c1[3:])
print(c1[:7])
print(c1[-1:-4])
print(c1[-1:-4:-1])

10
80
[10 20 30 40 50 60 70 80]
[40 50 60 70 80]
[10 20 30 40 50 60 70]
[]
[80 70 60]


In [22]:
c2 = np.array([[1,2,3],[4,5,6]])

In [23]:
print(c2[0,1])
print(c2[:1])
print(c2[1:])

2
[[1 2 3]]
[[4 5 6]]


================Array Operations (Vectorized) ==========

In [24]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a + b)
print(a * b)
print(a ** b)

[5 7 9]
[ 4 10 18]
[  1  32 729]


In [74]:
print(np.sqrt(a))
print(np.sin(a))
print(np.min(a))
print(np.sum(a))
print(np.max(b))
print(np.sum(b))
print(np.std(a))

[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]
1
6
6
15
0.816496580927726


==================== Reshaping & Flattening =========================

In [26]:
arr=np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
a1=arr.reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
flat=a1.flatten()
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
print(flat.T)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


============== Stacking & Splitting Arrays =================
np.hstack()	horizontal join
np.vstack()	vertical join
np.concatenate() general join

hstack → horizontal → side by side
vstack → vertical → top and bottom

hstack → horizontal → rows must match
vstack → vertical → columns must match

In [30]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [31]:
hstack=np.hstack([a,b])  # Rows must match, NumPy places b to the right of a.
hstack 

array([1, 2, 3, 4, 5, 6])

In [32]:
vstack=np.vstack([a,b]) # NumPy places b below a.
vstack

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
p=np.array([1,2])
q=np.array([5,6])
print(np.vstack([p,q]))

[[1 2]
 [5 6]]


In [34]:
parts=np.array_split(arr,3)
parts

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [88]:
arr = np.arange(10) #np.split always splits arrays in equal divisions
np.split(arr,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

================= Boolean Masking & Fancy Indexing ============
Boolean indexing returns a 1D array of selected elements.

In [35]:
arr = np.array([10, 20, 30, 40, 50])
mask= arr>25
print(mask)
print(arr[mask])
np.concatenate([a,b], axis=0)

[False False  True  True  True]
[30 40 50]


array([1, 2, 3, 4, 5, 6])

In [36]:
p = np.array([[1,2,3],[4,5,6]])
print(p[p>2])
print(p[p>3])

[3 4 5 6]
[4 5 6]


In [37]:
print(p[(p>2) & (p<6)])


[3 4 5]


In [38]:
print(arr[[1,1,3]]) # 1 1 3 means 1st index eleme 1st index ele and 3rd index element

[20 20 40]


==========================   BROADCASTING OF NUMPY ARRAYS   ==========================
Broadcasting allows operations between arrays of different shapes.

a = column vector
b = row vector
Column + Row → matrix

In [83]:
arr = np.array([1,2,3])
result=arr + 5
print(result)

[6 7 8]


In [84]:
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])
r= a+b
print(r)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


================================ Linear Algebra =================
Eigenvector = direction that doesn't change
Eigenvalue = amount of stretching

In [96]:
a=np.arange(1,4)
print(a)
print(b)
print(np.dot(a,b)) #The dot product multiplies corresponding elements and adds them.
print(a @ b) #The dot product is also defined like this



A = np.array([[1,2],
              [3,4]])

[1 2 3]
[10 20 30]
140


np.int64(140)

In [102]:
A = np.array([[1,2],
              [3,4]])

#print(np.linalg.det(A)) #Determinant of A, A → must be a square matrix (same number of rows and columns)
#print((np.linalg.inv(A))) # The inverse matrix is a matrix which, when multiplied by the original matrix, gives the identity matrix.
print(np.linalg.eig(A))   #compute the eigenvalues and eigenvectors of a square matrix.


EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


======================= Saving and Loading Arrays ==================

In [104]:
np.save("data.npy", arr)
np.load("data.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
arr = np.arange(1000000)
print(arr * 2)

[      0       2       4 ... 1999994 1999996 1999998]


========================

In [39]:
np.arange(10) #print values within interval

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [41]:
np.arange(10,20,5) #Acts like range
np.arange(10,21,5)

array([10, 15, 20])

In [42]:
np.arange(10,20,5,2)

TypeError: Cannot interpret '2' as a data type

In [43]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [44]:
np.zeros(5,dtype=int) #Hyperparameter tunning

array([0, 0, 0, 0, 0])

In [45]:
np.zeros([5,2],dtype=int) #try multid array

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [46]:
np.ones([3,7],dtype=int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [47]:
np.arange(-20,10) #1st arg less than 2nd arg

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [48]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
np.twos(3)

AttributeError: module 'numpy' has no attribute 'twos'

In [50]:
np.random.rand(3,2)

array([[0.66957106, 0.66479284],
       [0.97829596, 0.52616471],
       [0.31109163, 0.13384698]])

In [51]:
np.random.rand(5)

array([0.83156165, 0.53648774, 0.03147546, 0.83994598, 0.72783501])

In [52]:
np.random.rand(3,2)

array([[0.15916571, 0.87112462],
       [0.2700418 , 0.07464271],
       [0.06634756, 0.22962727]])

In [53]:
np.random.randint(3) #gives random value between 0 to 2

0

In [54]:
np.random.randint(5,10)

5

In [55]:
np.random.randint(5,10,3)

array([7, 5, 7], dtype=int32)

In [56]:
ra= np.random.randint(5,10,3)
print(ra)

[7 9 7]


In [57]:
otp= np.random.randint(5,10,4)
print(otp)

[7 6 6 5]


In [58]:
arr1=np.random.randint(10,40,(10,10))
print(arr1)

[[39 15 29 18 35 24 18 36 28 14]
 [11 19 34 33 17 11 21 19 16 29]
 [31 31 14 34 36 14 35 27 24 14]
 [12 12 31 36 21 27 12 10 35 17]
 [36 34 25 14 33 13 32 10 32 13]
 [19 17 33 24 13 36 37 33 35 18]
 [33 29 24 10 27 22 28 20 36 15]
 [32 34 26 24 25 34 21 11 37 31]
 [32 17 36 10 31 22 22 13 10 20]
 [16 25 38 20 16 10 33 36 27 12]]


In [59]:
arr1[3:4,2:6]


array([[31, 36, 21, 27]], dtype=int32)

In [60]:
test=np.random.randint(1,4,(3,3))
print(test)


[[1 2 3]
 [1 2 1]
 [3 2 3]]


In [61]:
test[0,2]

np.int32(3)

In [62]:
test[0:2]

array([[1, 2, 3],
       [1, 2, 1]], dtype=int32)

In [67]:
print(test[0]) # 1st row
print(test[1]) # 2nd row
print(test[2]) # 3rd row

[1 2 3]
[1 2 1]
[3 2 3]


In [68]:
print(test[:,0]) # 1st column
print(test[:,1]) # 2nd column
print(test[:,2]) # 3rd column

[1 1 3]
[2 2 2]
[3 1 3]


In [69]:
print(test[1,2])

1


In [70]:
arr1

array([[39, 15, 29, 18, 35, 24, 18, 36, 28, 14],
       [11, 19, 34, 33, 17, 11, 21, 19, 16, 29],
       [31, 31, 14, 34, 36, 14, 35, 27, 24, 14],
       [12, 12, 31, 36, 21, 27, 12, 10, 35, 17],
       [36, 34, 25, 14, 33, 13, 32, 10, 32, 13],
       [19, 17, 33, 24, 13, 36, 37, 33, 35, 18],
       [33, 29, 24, 10, 27, 22, 28, 20, 36, 15],
       [32, 34, 26, 24, 25, 34, 21, 11, 37, 31],
       [32, 17, 36, 10, 31, 22, 22, 13, 10, 20],
       [16, 25, 38, 20, 16, 10, 33, 36, 27, 12]], dtype=int32)

In [71]:
arr1[3:4, 2:6]

array([[31, 36, 21, 27]], dtype=int32)

In [72]:
arr1[2:5, 3:8]

array([[34, 36, 14, 35, 27],
       [36, 21, 27, 12, 10],
       [14, 33, 13, 32, 10]], dtype=int32)

In [73]:
arr1[1:5, 4:9]

array([[17, 11, 21, 19, 16],
       [36, 14, 35, 27, 24],
       [21, 27, 12, 10, 35],
       [33, 13, 32, 10, 32]], dtype=int32)

In [127]:
arr1 = np.random.randint(1,5,(3,3))
print(arr1)

[[2 3 3]
 [3 3 3]
 [4 3 4]]


In [130]:
arr1[0:2] #print only rows
arr1[1:2] #print only 1st row

array([[2, 3, 3],
       [3, 3, 3]], dtype=int32)

In [131]:
print(arr1)

[[2 3 3]
 [3 3 3]
 [4 3 4]]


In [133]:
print(arr)

[     0      1      2 ... 999997 999998 999999]


In [136]:
arr0=np.random.randint(1,6,(10,10))
arr0

array([[1, 2, 2, 2, 2, 1, 4, 1, 5, 5],
       [1, 2, 5, 4, 1, 5, 3, 3, 5, 1],
       [4, 4, 3, 3, 5, 3, 1, 1, 3, 3],
       [1, 3, 1, 1, 5, 4, 4, 2, 5, 3],
       [4, 1, 2, 1, 4, 5, 2, 2, 1, 5],
       [4, 5, 4, 2, 3, 3, 1, 3, 4, 3],
       [5, 5, 2, 3, 3, 1, 5, 1, 3, 4],
       [1, 5, 5, 5, 1, 5, 1, 4, 1, 2],
       [2, 4, 4, 1, 5, 2, 5, 5, 1, 2],
       [2, 5, 4, 4, 5, 5, 1, 2, 4, 5]], dtype=int32)

In [137]:
arr0[: : -1]

array([[2, 5, 4, 4, 5, 5, 1, 2, 4, 5],
       [2, 4, 4, 1, 5, 2, 5, 5, 1, 2],
       [1, 5, 5, 5, 1, 5, 1, 4, 1, 2],
       [5, 5, 2, 3, 3, 1, 5, 1, 3, 4],
       [4, 5, 4, 2, 3, 3, 1, 3, 4, 3],
       [4, 1, 2, 1, 4, 5, 2, 2, 1, 5],
       [1, 3, 1, 1, 5, 4, 4, 2, 5, 3],
       [4, 4, 3, 3, 5, 3, 1, 1, 3, 3],
       [1, 2, 5, 4, 1, 5, 3, 3, 5, 1],
       [1, 2, 2, 2, 2, 1, 4, 1, 5, 5]], dtype=int32)

In [138]:
arr0[: : -2]

array([[2, 5, 4, 4, 5, 5, 1, 2, 4, 5],
       [1, 5, 5, 5, 1, 5, 1, 4, 1, 2],
       [4, 5, 4, 2, 3, 3, 1, 3, 4, 3],
       [1, 3, 1, 1, 5, 4, 4, 2, 5, 3],
       [1, 2, 5, 4, 1, 5, 3, 3, 5, 1]], dtype=int32)

In [141]:
arr=np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [142]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [143]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [145]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [146]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [147]:
arr0

array([[1, 2, 2, 2, 2, 1, 4, 1, 5, 5],
       [1, 2, 5, 4, 1, 5, 3, 3, 5, 1],
       [4, 4, 3, 3, 5, 3, 1, 1, 3, 3],
       [1, 3, 1, 1, 5, 4, 4, 2, 5, 3],
       [4, 1, 2, 1, 4, 5, 2, 2, 1, 5],
       [4, 5, 4, 2, 3, 3, 1, 3, 4, 3],
       [5, 5, 2, 3, 3, 1, 5, 1, 3, 4],
       [1, 5, 5, 5, 1, 5, 1, 4, 1, 2],
       [2, 4, 4, 1, 5, 2, 5, 5, 1, 2],
       [2, 5, 4, 4, 5, 5, 1, 2, 4, 5]], dtype=int32)

In [149]:
arr0 <3

array([[ True,  True,  True,  True,  True,  True, False,  True, False,
        False],
       [ True,  True, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False, False, False,  True,  True, False,
        False],
       [ True, False,  True,  True, False, False, False,  True, False,
        False],
       [False,  True,  True,  True, False, False,  True,  True,  True,
        False],
       [False, False, False,  True, False, False,  True, False, False,
        False],
       [False, False,  True, False, False,  True, False,  True, False,
        False],
       [ True, False, False, False,  True, False,  True, False,  True,
         True],
       [ True, False, False,  True, False,  True, False, False,  True,
         True],
       [ True, False, False, False, False, False,  True,  True, False,
        False]])

In [152]:
arr0[arr0 == 4]

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4], dtype=int32)